package com.example.SuperMarket.dto;


import lombok.Data;

@Data
public class UserRequestDTO {

    // No need for id because it will be generated by the DB
    private String username;
    private String email;
    private String password;
    private String address;
    private String phoneNumber;
    // No need for role
}
